import pytest
from sqlalchemy.orm import Session
from modules.users.models import User
from modules.users.repo import (
    create_user,
    get_user_by_id,
    get_user_by_username,
    get_user_by_email,
    get_user_by_username_or_email
)
from db import SessionLocal, Base, engine

"""
This test file is generated by AI. But the function is implement by Yulin Liu
"""

@pytest.fixture
def db_session():
    """
    Create a fresh database session for each test.
    Creates all tables before the test and drops them after.
    """
    Base.metadata.create_all(bind=engine)
    session = SessionLocal()
    yield session
    session.close()
    Base.metadata.drop_all(bind=engine)


@pytest.fixture
def sample_user():
    """
    Create a sample user object for testing.
    """
    user = User(
        username="testuser",
        email="test@example.com",
        password_hash="hashed_password_123"
    )
    return user


class TestCreateUser:
    """Test cases for create_user function."""

    def test_create_user_success(self, db_session: Session, sample_user: User):
        """Test successful user creation."""
        created_user = create_user(db_session, sample_user)
        
        assert created_user.id is not None
        assert created_user.username == "testuser"
        assert created_user.email == "test@example.com"
        assert created_user.password_hash == "hashed_password_123"
        assert created_user.is_deleted == 0

    def test_create_user_with_different_values(self, db_session: Session):
        """Test creating user with different values."""
        user = User(
            username="john_doe",
            email="john@example.com",
            password_hash="hash_abc123"
        )
        created_user = create_user(db_session, user)
        
        assert created_user.username == "john_doe"
        assert created_user.email == "john@example.com"

    def test_create_user_persists_to_database(self, db_session: Session, sample_user: User):
        """Test that created user is persisted to database."""
        created_user = create_user(db_session, sample_user)
        user_id = created_user.id
        
        # Retrieve the user from database using a new query
        retrieved_user = db_session.get(User, user_id)
        assert retrieved_user is not None
        assert retrieved_user.username == "testuser"


class TestGetUserById:
    """Test cases for get_user_by_id function."""

    def test_get_user_by_id_success(self, db_session: Session, sample_user: User):
        """Test retrieving user by valid ID."""
        created_user = create_user(db_session, sample_user)
        
        retrieved_user = get_user_by_id(db_session, created_user.id)
        
        assert retrieved_user is not None
        assert retrieved_user.id == created_user.id
        assert retrieved_user.username == "testuser"

    def test_get_user_by_id_not_found(self, db_session: Session):
        """Test getting user with non-existent ID returns None."""
        result = get_user_by_id(db_session, 9999)
        
        assert result is None

    def test_get_user_by_id_multiple_users(self, db_session: Session):
        """Test retrieving correct user when multiple users exist."""
        user1 = User(username="user1", email="user1@example.com", password_hash="hash1")
        user2 = User(username="user2", email="user2@example.com", password_hash="hash2")
        
        created_user1 = create_user(db_session, user1)
        created_user2 = create_user(db_session, user2)
        
        retrieved_user = get_user_by_id(db_session, created_user2.id)
        
        assert retrieved_user.username == "user2"


class TestGetUserByUsername:
    """Test cases for get_user_by_username function."""

    def test_get_user_by_username_success(self, db_session: Session, sample_user: User):
        """Test retrieving user by valid username."""
        create_user(db_session, sample_user)
        
        retrieved_user = get_user_by_username(db_session, "testuser")
        
        assert retrieved_user is not None
        assert retrieved_user.username == "testuser"
        assert retrieved_user.email == "test@example.com"

    def test_get_user_by_username_not_found(self, db_session: Session):
        """Test getting user with non-existent username returns None."""
        result = get_user_by_username(db_session, "nonexistent")
        
        assert result is None

    def test_get_user_by_username_case_sensitive(self, db_session: Session, sample_user: User):
        """Test that username search is case-sensitive."""
        create_user(db_session, sample_user)
        
        result = get_user_by_username(db_session, "TestUser")
        
        assert result is None

    def test_get_user_by_username_multiple_users(self, db_session: Session):
        """Test retrieving correct user when multiple users exist."""
        user1 = User(username="alice", email="alice@example.com", password_hash="hash1")
        user2 = User(username="bob", email="bob@example.com", password_hash="hash2")
        
        create_user(db_session, user1)
        create_user(db_session, user2)
        
        retrieved_user = get_user_by_username(db_session, "bob")
        
        assert retrieved_user.username == "bob"
        assert retrieved_user.email == "bob@example.com"


class TestGetUserByEmail:
    """Test cases for get_user_by_email function."""

    def test_get_user_by_email_success(self, db_session: Session, sample_user: User):
        """Test retrieving user by valid email."""
        create_user(db_session, sample_user)
        
        retrieved_user = get_user_by_email(db_session, "test@example.com")
        
        assert retrieved_user is not None
        assert retrieved_user.email == "test@example.com"
        assert retrieved_user.username == "testuser"

    def test_get_user_by_email_not_found(self, db_session: Session):
        """Test getting user with non-existent email returns None."""
        result = get_user_by_email(db_session, "notfound@example.com")
        
        assert result is None

    def test_get_user_by_email_case_sensitive(self, db_session: Session, sample_user: User):
        """Test that email search is case-sensitive."""
        create_user(db_session, sample_user)
        
        result = get_user_by_email(db_session, "TEST@EXAMPLE.COM")
        
        assert result is None

    def test_get_user_by_email_multiple_users(self, db_session: Session):
        """Test retrieving correct user when multiple users exist."""
        user1 = User(username="user1", email="email1@example.com", password_hash="hash1")
        user2 = User(username="user2", email="email2@example.com", password_hash="hash2")
        
        create_user(db_session, user1)
        create_user(db_session, user2)
        
        retrieved_user = get_user_by_email(db_session, "email2@example.com")
        
        assert retrieved_user.username == "user2"


class TestGetUserByUsernameOrEmail:
    """Test cases for get_user_by_username_or_email function."""

    def test_get_user_by_username_or_email_with_username(self, db_session: Session, sample_user: User):
        """Test retrieving user by username using username_or_email function."""
        create_user(db_session, sample_user)
        
        retrieved_user = get_user_by_username_or_email(db_session, "testuser")
        
        assert retrieved_user is not None
        assert retrieved_user.username == "testuser"

    def test_get_user_by_username_or_email_with_email(self, db_session: Session, sample_user: User):
        """Test retrieving user by email using username_or_email function."""
        create_user(db_session, sample_user)
        
        retrieved_user = get_user_by_username_or_email(db_session, "test@example.com")
        
        assert retrieved_user is not None
        assert retrieved_user.email == "test@example.com"

    def test_get_user_by_username_or_email_not_found(self, db_session: Session):
        """Test getting user with non-existent username or email returns None."""
        result = get_user_by_username_or_email(db_session, "nonexistent")
        
        assert result is None

    def test_get_user_by_username_or_email_prioritizes_username_match(self, db_session: Session):
        """Test that function returns user when username matches."""
        user1 = User(username="alice", email="alice@example.com", password_hash="hash1")
        user2 = User(username="bob", email="bob@example.com", password_hash="hash2")
        
        create_user(db_session, user1)
        create_user(db_session, user2)
        
        retrieved_user = get_user_by_username_or_email(db_session, "alice")
        
        assert retrieved_user.username == "alice"

    def test_get_user_by_username_or_email_matches_email(self, db_session: Session):
        """Test that function returns user when email matches."""
        user = User(username="testuser", email="test@example.com", password_hash="hash1")
        create_user(db_session, user)
        
        retrieved_user = get_user_by_username_or_email(db_session, "test@example.com")
        
        assert retrieved_user.email == "test@example.com"

    def test_get_user_by_username_or_email_case_sensitive(self, db_session: Session, sample_user: User):
        """Test that search is case-sensitive."""
        create_user(db_session, sample_user)
        
        result = get_user_by_username_or_email(db_session, "TESTUSER")
        
        assert result is None

