//This file is partially generated by AI.
import { reactive } from "vue";

const STORAGE_KEY = "uiSettings";

export const THEME_OPTIONS = [
  { label: "Blue", value: "blue", color: "#1677ff" },
  { label: "Yellow", value: "yellow", color: "#faad14" },
  { label: "Green", value: "green", color: "#52c41a" },
  { label: "Red", value: "red", color: "#f5222d" },
];

const THEME_MAP = {
    blue: "#1677ff",
    yellow: "#faad14",
    green: "#52c41a",
    red: "#f5222d",
  };
  
const FONT_SIZE_MAP = {
  small: "12px",
  medium: "14px",
  large: "16px",
};
const THEME_HOME_BACKGROUND_MAP = {
  blue: {
    radial: "rgba(37, 99, 235, 0.15)",
    top: "#f1f5f9",
    mid: "#f8fafc",
    bottom: "#f1f5f9",
  },
  yellow: {
    radial: "rgba(196, 156, 67, 0.12)",
    top: "#fcf9f1",
    mid: "#fdfaf4",
    bottom: "#f7f1df",
  },
  green: {
    radial: "rgba(74, 132, 100, 0.12)",
    top: "#f2f8f4",
    mid: "#f6faf7",
    bottom: "#e7f0e9",
  },
  red: {
    radial: "rgba(176, 92, 92, 0.11)",
    top: "#faf4f4",
    mid: "#fcf7f7",
    bottom: "#f3e7e7",
  },
};

const defaults = {
  theme: "blue",
  darkMode: false,
  fontSize: "medium",
  fontType: "default",
};

export const uiSettings = reactive({ ...defaults });

//check if user is logged in
function isLogin() {
    const token = localStorage.getItem("authToken");
    const isGuest = localStorage.getItem("authGuest");
    return token && !isGuest;}
//get theme color
export function getThemeColor(themeName) {
  return THEME_MAP[themeName] || THEME_MAP[defaults.theme];
}
//get home page background
export function getHomePageBackground(themeName) {
  return THEME_HOME_BACKGROUND_MAP[themeName] || THEME_HOME_BACKGROUND_MAP[defaults.theme];
}
//get font size 
export function getFontSizeToken(fontSizeConfig) {
  const size = FONT_SIZE_MAP[fontSizeConfig] || FONT_SIZE_MAP[defaults.fontSize];
  return parseFloat(size);
}

function getFontSize(fontSizeConfig) {
  return FONT_SIZE_MAP[fontSizeConfig] || FONT_SIZE_MAP[defaults.fontSize];
}


//save settings to local storage
function saveSettings() {
  localStorage.setItem(
    STORAGE_KEY,
    JSON.stringify({
      theme: uiSettings.theme,
      fontSize: uiSettings.fontSize,
    }),
  );
}

export function getPalette() {
  return {
    bg: "#f5f7fb",
    text: "#1f2937",
    surface: "#ffffff",
    border: "#eef0f3",
    subtext: "#6b7280",
  };
}

//reset to default theme
function resetToDefaultTheme() {
  Object.assign(uiSettings, defaults);
}
//apply theme
function applyTheme(theme) {
    const root = document.documentElement;
    const bg = getHomePageBackground(theme);
  
    root.style.setProperty("--app-primary", getThemeColor(theme));
    root.style.setProperty("--home-bg-radial", bg.radial);
    root.style.setProperty("--home-bg-top", bg.top);
    root.style.setProperty("--home-bg-mid", bg.mid);
    root.style.setProperty("--home-bg-bottom", bg.bottom);
}

//apply font size
function applyFontSize(fontSize) {
    const root = document.documentElement;
    const size = getFontSize(fontSize);
  
    root.style.setProperty("--app-font-size", size);
    root.style.fontSize = size;
  
    if (document.body) {
      document.body.style.fontSize = size;
    }
}
//apply settings
function applySettings() {
    const theme = isLogin()? uiSettings.theme: defaults.theme;
    const fontSize = isLogin()? uiSettings.fontSize: defaults.fontSize;
    applyTheme(theme);
    applyFontSize(fontSize);
    document.documentElement.setAttribute("data-theme", "light");
  }


export function initUiSettings() {
  if (!isLogin()) {
    resetToDefaultTheme();
    applySettings();
    return;
  }
  const saved = localStorage.getItem(STORAGE_KEY);
  if (saved) {
    try {
      const parsed = JSON.parse(saved);
      Object.assign(uiSettings, defaults, {
        theme: parsed?.theme,
        fontSize: parsed?.fontSize,
      });
    } catch {
      resetToDefaultTheme();
    }
  } else {
    resetToDefaultTheme();
  }
  applySettings();
}
//update ui settings
export function updateUiSettings(partial) {
    if (!isLogin()) {
      resetToDefaultTheme();
      applySettings();
      return;
    }
  
    if (partial.theme) {
      uiSettings.theme = THEME_MAP[partial.theme]? partial.theme: defaults.theme;
    }
  
    if (partial.fontSize) {
      uiSettings.fontSize = FONT_SIZE_MAP[partial.fontSize] ? partial.fontSize : defaults.fontSize;
    }
  saveSettings();
    applySettings();
  }

//reset ui theme to default
export function resetUiThemeToDefault() {
  localStorage.removeItem(STORAGE_KEY);
  resetToDefaultTheme();
  applySettings();
}
