<template>
  <div class="body-container">
    <div ref="gridRef" class="grid">
      <TaskGroupCard title="Important & Urgent" color="red" :task-level="1" :initialItems="urgentImportant"
        @reload="loadTasks" @task-moved="handleTaskMoved" />
      <TaskGroupCard title="Important but Not Urgent" color="yellow" :task-level="2" :initialItems="importantNotUrgent"
        @reload="loadTasks" @task-moved="handleTaskMoved" />
      <TaskGroupCard title="Not Important but Urgent" color="blue" :task-level="3" :initialItems="urgentNotImportant"
        @reload="loadTasks" @task-moved="handleTaskMoved" />
      <TaskGroupCard title="Not Important & Not Urgent" color="green" :task-level="4"
        :initialItems="notUrgentNotImportant" @reload="loadTasks" @task-moved="handleTaskMoved" />
    </div>
    <a-dropdown placement="topRight" :trigger="['hover']">
      <a-button type="primary" shape="circle" size="large" class="export-btn">
        <template #icon>
          <DownloadOutlined />
        </template>
      </a-button>
      <template #overlay>
        <a-menu @click="exportTasks">
          <a-menu-item key="image">Export as Image</a-menu-item>
          <a-menu-item key="excel">Export as Excel</a-menu-item>
        </a-menu>
      </template>
    </a-dropdown>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import TaskGroupCard from '../components/TaskGroupCard.vue'
import { getTaskList, updateTask } from '../api/tasks'
import { DownloadOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import * as XLSX from 'xlsx'
import domtoimage from 'dom-to-image-more'



const LEVEL_LABEL = {
  1: 'Important & Urgent',
  2: 'Important but Not Urgent',
  3: 'Not Important but Urgent',
  4: 'Not Important & Not Urgent',
}

const taskList = ref([])
async function loadTasks() {
  try {
    taskList.value = await getTaskList()
  } catch (e) {
    console.error(e)
  }
}

onMounted(() => {
  loadTasks()
})

function getUrgentImportantTasks() {
  return taskList.value.filter(t => t.task_level === 1)
}
function getImportantNotUrgentTasks() {
  return taskList.value.filter(t => t.task_level === 2)
}
function getUrgentNotImportantTasks() {
  return taskList.value.filter(t => t.task_level === 3)
}

function getNotUrgentNotImportantTasks() {
  return taskList.value.filter(t => t.task_level === 4)
}


const urgentImportant = computed(getUrgentImportantTasks)
const importantNotUrgent = computed(getImportantNotUrgentTasks)
const urgentNotImportant = computed(getUrgentNotImportantTasks)
const notUrgentNotImportant = computed(getNotUrgentNotImportantTasks)

// The code is partially generated by AI.

const gridRef = ref(null)

function preparePaginationExportStyles() {
  const style = document.createElement('style')
  style.id = 'export-pagination-style'
  style.textContent = `
.ant-pagination-item-active,
.ant-pagination-item-active button,
.ant-pagination-item-active a,
.ant-pagination-item-active span,
.ant-pagination-item-active * {
  background-color: #1890ff !important;
  border-color: #1890ff !important;
  color: #fff !important;
}
.ant-pagination-item-active button,
.ant-pagination-item-active a {
  color: #fff !important;
}
.cards-group .card-body {
  padding-bottom: 90px !important;
}
.ant-list-pagination {
  position: relative !important;
  margin-top: 30px !important;
}
.cards-group .task-list .ant-list-item {
  padding: 5px 8px !important;
}
`
  document.head.appendChild(style)
  return style
}

function restorePaginationStyles(styleElement) {
  if (styleElement && styleElement.parentNode) {
    styleElement.parentNode.removeChild(styleElement)
  }
}

async function exportToImage() {
  if (!gridRef.value) return message.error('Image exported failed')
  const styleElement = preparePaginationExportStyles()
  try {
    const blob = await domtoimage.toBlob(gridRef.value, {
      bgcolor: '#f5f7fb',
      cacheBust: true,
      pixelRatio: 2,
      style: {
        transformOrigin: 'top left',
      },
    })
    const downloadLink = document.createElement('a')
    downloadLink.download = 'tasks.png'
    downloadLink.href = URL.createObjectURL(blob)
    downloadLink.click()
    URL.revokeObjectURL(downloadLink.href)
    message.success('Image exported')
  } catch (error) {
    console.error(error)
    message.error('Image exported failed')
  } finally {
    restorePaginationStyles(styleElement)
  }
}


async function exportToExcel() {
  try {
    const latestTasks = await getTaskList()
    const tasks = latestTasks.map(t => ({
      Title: t.title,
      Due: t.dueDate || '',
      Done: t.done ? 'Yes' : 'No',
      Level: LEVEL_LABEL[t.task_level] || 'Unknown',
    }))
    const sheet = XLSX.utils.json_to_sheet(tasks)
    const excel = XLSX.utils.book_new()
    // Set column widths based on content
    const headers = ['Title', 'Due', 'Done', 'Level']
    sheet['!cols'] = headers.map((key) => {
      const maxLen = Math.max(
        key.length,
        ...tasks.map((r) => String(r[key] ?? '').length)
      )
      return { wch: Math.min(maxLen + 2, 50) }
    })
    XLSX.utils.book_append_sheet(excel, sheet, 'Tasks')
    XLSX.writeFile(excel, 'tasks.xlsx')
  } catch (error) {
    console.error(error)
    message.error(error?.message || 'unable to fetch latest tasks!')
  }
}

function exportTasks({ key }) {
  if (key === 'image') {
    exportToImage()
  }
  if (key === 'excel') {
    exportToExcel()
  }
}

async function handleTaskMoved({ id, toLevel }) {
  try {
    await updateTask(id, { task_level: toLevel })
    message.success('Task urgency updated.')
    await loadTasks()
  } catch (e) {
    console.error(e)
    message.error(e?.message || 'Failed to move task.')
  }
}
</script>

<style scoped>
.body-container {
  margin: 0 auto;
  /* padding: 20px 50px; */
  position: relative;
}

.grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 30px;
  padding: 20px;
}

.export-btn {
  position: fixed;
  right: 30px;
  bottom: 30px;
  z-index: 200;
}


@media (max-width: 960px) {
  .grid {
    grid-template-columns: 1fr;
  }
}
</style>