<!-- This file is partially generated by AI. -->
<template>
<div class="settings-page">
    <a-card title="Settings">
        <div class="setting-block">
            <div class="settings-block">
                <div class="settings-type">Theme</div>
                <a-select
                  :value="uiSettings.theme"
                  placeholder="Select Theme"
                  style="width: 100%"
                  @change="onThemeChange">
                    <a-select-option
                      v-for="theme in THEME_OPTIONS"
                      :key="theme.value"
                      :value="theme.value">
                      {{ theme.label }}
                    </a-select-option>
                </a-select>
            </div>

            <div class="settings-block">
                <div class="settings-type">Font Size</div>
                <a-select
                  :value="uiSettings.fontSize"
                  placeholder="Select Font Size"
                  style="width: 100%"
                  @change="onFontSizeChange">
                    <a-select-option value="small">Small</a-select-option>
                    <a-select-option value="medium">Medium</a-select-option>
                    <a-select-option value="large">Large</a-select-option>
                </a-select>
            </div>

            <div class="settings-block">
                <div class="settings-type">Font Type</div>
                <a-select
                  :value="uiSettings.fontType"
                  placeholder="Select Font Type"
                  style="width: 100%"
                  @change="onFontTypeChange">
                    <a-select-option value="default">Default</a-select-option>
                    <a-select-option value="serif">Serif</a-select-option>
                    <a-select-option value="TimesNewRoman">Times New Roman</a-select-option>
                </a-select>
            </div>
        </div>
        <div class="reset-block">
        <a-button type="default" danger @click="onResetToDefault">
          Reset to Default
        </a-button>
        </div>
    </a-card>
</div>
</template>



<script setup>
import { THEME_OPTIONS, uiSettings, updateUiSettings, resetUiThemeToDefault } from "../stores/uiSettings";
import { Modal, message } from "ant-design-vue";

function onThemeChange(value) {
  updateUiSettings({ theme: value });
}

function onFontSizeChange(value) {
  updateUiSettings({ fontSize: value });
}

function onFontTypeChange(value) {
  updateUiSettings({ fontType: value });
}

  function onResetToDefault() {
    Modal.confirm({
      title: "Reset to Default",
      content: "Do you want to reset your theme and font settings to default?",
      onOk() {
        resetUiThemeToDefault();
        message.success("Theme and font settings have been reset to default.");
      },
    });
}

</script>


<style scoped>
.settings-page {
  max-width: 800px;
  margin: 0 auto;
  color: var(--app-text);
}

.setting-block {
  display: flex;
  flex-direction: column;
  gap: 24px;
}


.settings-block {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.settings-type {  
    font-weight: 600;
}

.reset-block {
  margin-top: 32px;
  display: flex;
  justify-content: flex-start;
}

</style>